language: bash
sudo: true

language: go
go_import_path: github.ibm.com/IBMPrivateCloud/icp-cert-policy-controller
go:
  - 1.12.9

services:
  - docker

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/
    - klog

matrix:
  fast_finish: true

before_install:
  - source travis-env.sh

stages:
  - build

jobs:
  include:
    - stage: build
      os: linux
      script:
        - make init
        - make build
        - make image
        - make docker:login
        - make docker-push

