language: bash
sudo: true

language: go
go_import_path: github.ibm.com/IBMPrivateCloud/PolicyFramework
go:
  - 1.12

services:
  - docker

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

matrix:
  fast_finish: true

before_install:
  - source travis-env.sh

stages:
  - lint
  - test
  - build

jobs:
  include:
    - stage: lint
      script:
        - make lint
    - stage: test
      os: linux
      script:
        - make test
    - stage: build
      os: linux
      script:
        - make init
        - make build
        - make image
        - make docker:login
        - make docker-push
        - make rhel-image
        - make docker-push-rhel
